### ISSUE TITLE
Multiple network devices

### ISSUE THREAD

**Issue by Joel-Muller** [greshake/i3status-rust#1866]
Hi!

Would nice if it was possible to set multiple network devices in the bar like battery (BAT1, BAT2)

Thanks

**Comment by MaxVerevkin** [comment]
> like battery (BAT1, BAT2)

Can you elaborate please? Do you mean that your block shows either BAT1 or BAT2?

**Comment by Joel-Muller** [comment]
No I want display multiple network devices like wlan,lan at the same time like is possible to show to batteries. Is a request for a feature not a bug.

**Comment by GladOSkar** [comment]
What's wrong with just using multiple `net` blocks? That's what i do, and is how it's intended to be used.

**Comment by Joel-Muller** [comment]
I couldn't do two [net] blocks with a device as parameter. the bar displays me green words. It's because it is too long?

**Comment by Joel-Muller** [comment]
My config looks like this and it's display only one 

#```
 .config/i3status-rust/config.toml
icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon home: $available.eng(w:2) "


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon {$signal_strength $ssid $frequency} via $device IPv4: $ip UP: $speed_up DOWN:  $speed_down"
missing_format = "No Wireless"
interval = 1

[[block]]
block = "net"
device = "enp58s0u1u3c2"
format = " $icon $device IPv4: $ip UP: $speed_up DOWN:  $speed_down"
missing_format = "No Ethernet"
interval = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "80:C3:BA:29:FE:97"
disconnected_format = " $icon NO DEVICE"
format = " $icon MOMENTUM4"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
```

**Comment by MaxVerevkin** [comment]
> the bar displays me green words.

Can you be more precise?

By the way, missing_format was broken, fixed in cb99454

**Comment by MaxVerevkin** [comment]
Can you share a screenshot?

**Comment by Joel-Muller** [comment]
Yes. I will reproduce when I’am on the laptop

**Comment by Joel-Muller** [comment]
[https://abload.de/img/20230415_21h04m05s_gr6pdkq.png](url)

I couldn't reproduce the exact error but still no second net display on the bar.
The i3status-bar version is on the picture should be the newest.

cat ~/.config/i3status-rust/config.toml
``
# .config/i3status-rust/config.toml
icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon home: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home/backup"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon backup: $available.eng(w:2) "


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon {$signal_strength $ssid $frequency} via $device IPv4: $ip $speed_up DOWN:  $speed_down"
missing_format = "No Wireless"
interval = 1

[[block]]
block = "net"
device = "enp58s0u1u3c2"
format = " $icon $device IPv4: $ip UP: $speed_up DOWN:  $speed_down"
missing_format = "No Ethernet"
interval = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "80:C3:BA:29:FE:97"
disconnected_format = " $icon NO DEVICE"
``

That my config

**Comment by MaxVerevkin** [comment]
@Joel-Muller can you try the latest master version?

**Comment by Joel-Muller** [comment]
[Screenshot](https://abload.de/image.php?img=20230416_12h52m41s_grh7csn.png)

Now No Ethernet is displayed but I have a Ethernet connection
Look at screenshot also the version uf i3status-rs is displayed on it

Cheers

**Comment by MaxVerevkin** [comment]
@Joel-Muller Can you test https://github.com/greshake/i3status-rust/tree/net_inactive_fmt branch? It adds `inactive_format = "..."` option to distinguish between missing interfaces and just inactive ones.

**Comment by Joel-Muller** [comment]
With old config
https://abload.de/img/20230416_16h09m30s_grr0f77.png

Shows me NO ETH but I have a ethernet and internet connection
`
With new following config
# .config/i3status-rust/config.toml
icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon home: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home/backup"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon backup: $available.eng(w:2) "


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon {$signal_strength $ssid $frequency} via $device IPv4: $ip $speed_up DOWN:  $speed_down"
inactive_format = "No Wireless"
interval = 1

[[block]]
block = "net"
device = "enp58s0u1u3c2"
format = " $icon $device IPv4: $ip UP: $speed_up DOWN:  $speed_down"
inactive_format = "No Ethernet"
interval = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[# .config/i3status-rust/config.toml
icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon home: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/home/backup"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon backup: $available.eng(w:2) "


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
device = "wlp0s20f3"
format = " $icon {$signal_strength $ssid $frequency} via $device IPv4: $ip $speed_up DOWN:  $speed_down"
inactive_format = "No Wireless"
interval = 1

[[block]]
block = "net"
device = "enp58s0u1u3c2"
format = " $icon $device IPv4: $ip UP: $speed_up DOWN:  $speed_down"
inactive_format = "No Ethernet"
interval = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "80:C3:BA:29:FE:97"
disconnected_format = " $icon NO DEVICE"
format = " $icon MOMENTUM4"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good
`
https://abload.de/img/20230416_16h06m23s_grjliqy.png

Looks at the terminal and ip a command with the output of the connection

**Comment by Joel-Muller** [comment]
I have to add that the Ethernet is plugged over USB-C (Displaylink)

**Comment by MaxVerevkin** [comment]
It is considered "inactive" because it has `state UNKNOWN`. Is it actually "up"?

**Comment by Joel-Muller** [comment]
Yes. A interface can’t be down with assigned IPv4 and IPv6’s.

**Comment by MaxVerevkin** [comment]
Hmm, should `lo` be considered up?

**Comment by Joel-Muller** [comment]
I would add if device = up | unknow then on to write code in words..... That should fix this issue.  lo is loopback. Why should be up?

**Comment by MaxVerevkin** [comment]
> Yes. A interface can’t be down with assigned IPv4 and IPv6’s.

> Why should be up?

Because it has `state UNKNOWN` and an IP address..? I don't quite understand how linux networking works, so feel free to propose your understandings of what "active interface" means.

**Comment by MaxVerevkin** [comment]
Once someone submits a patch/PR, yes.

**Comment by muellerjoel** [comment]
Great!

**Comment by MaxVerevkin** [comment]
It is still not clear to me how to check if interface is enabled/disabled. Currently we check if operstate is up. We can instead check if it's _not down_, but I'm not sure it's the best way to it.

**Comment by muellerjoel** [comment]
Check if operstate up OR unknow and have a IP

**Comment by muellerjoel** [comment]
I would exclude. I don't know why should displayed a loopback device.

**Comment by MaxVerevkin** [comment]
I suppose we can ignore IPs with `scope host`, which will exclude `lo`?

**Comment by muellerjoel** [comment]
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever`

lo have a scope host in the ip a command so you have to exclude too

**Comment by MaxVerevkin** [comment]
@muellerjoel Please try #1903

**Comment by muellerjoel** [comment]
I will give a soon as possible
