### ISSUE TITLE
Pacman Block fakeroot disposal

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#30]
@keeslinp : The pacman block clearly still has issues with cleaning up after updates. This is a screenshot of the process hierarchie after running for like 2h:

![2017-05-28-10 17 00](https://cloud.githubusercontent.com/assets/2379799/26527218/1ae8aac8-438f-11e7-8e20-950e6dc423bf.png)

**Comment by keeslinp** [comment]
Hmm, that's really strange. I took a look at it yesterday but for some reason the project wasn't​ building for me after recent changes. I'm gonna take a better look at it soon. I wonder if there's something you're supposed to call after spawn(). A new compiler warning popped up that complained about a return value not being used after spawn. I suspect that's relevant.

**Comment by greshake** [comment]
I really don't have time to help you a whole lot right now, but spawn() returns a handle to the child process and doesn't block until it's finished. You should use the handle to ensure all child processes are killed in the end. Also, try to update in a separate thread, that way other block updates don't stall until you've updated the package db. Actually, any update which queries network or does some other huge operation should be executed separately. Should have documented this and told you earlier, sorry about that, but I'm to my neck in other tasks right now. Look at the pending PR for the weather block; the guy did exactly that (his code is very nice). Use an Arc<Mutex<Msg>> to send data between your update thread and the main thread.

**Comment by greshake** [comment]
Oh, and no idea why it wasn't building, I tried paying attention not to push broken changes. Just checked and master is building fine, except for a couple warnings.

**Comment by keeslinp** [comment]
Thanks for the suggestion :). I don't know what was wrong either, I was getting some errors about missing things. I ended up just removing and recloning the repo and all was well. I'll make the changes you suggested.

**Comment by pitkley** [comment]
Since the refactor I did (#37) has been merged, can you (@greshake @keeslinp) check if you still have defunct processes? I have not experienced it since, but more data would be great :+1:

**Comment by greshake** [comment]
I'll keep an eye on it. by the way, I just noticed the click isn't working yet (you're not using a ButtonWidget)... Sorry for the big clusterfuck that is widgets and click handling right now.. Will be redone soon. Also, blocks that take a really long time to update currently block other blocks from updating. This will also be fixed with my partial rewrite.

**Comment by Peltoche** [comment]
Hi,
The issue is still running and is present in the spotify block too.

**Comment by pitkley** [comment]
@Peltoche are you running an up-to-date version of i3status-rust? This was probably fixed with cb8ac6b, at least I haven't experienced this issue since then.

Be careful: if you update to a relatively recent version, you will have to update your configuration from JSON to TOML, see [here](https://github.com/greshake/i3status-rust#configuration-changed) on how to do it.

**Comment by greshake** [comment]
@Peltoche I don't think this can be caused by the Music block. It's using a single thread to wait for Dbus signals, and it is only created on startup. Please elaborate if you have further information, 'is present' is not very helpful with a new issue. If the music block also has a thread leak, the issue won't be realted to the pacman block.

**Comment by Peltoche** [comment]
@pitkley an update fix it indeed, thanks.

**Comment by greshake** [comment]
Alright, I assume that this is resolved now. Closing
