### ISSUE TITLE
Music block length expanding/retracting during rotation

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#439]
While coming up for a fix for #435, I also tried to figure out why the below expanding/retracting bug occurs:

![recording](https://user-images.githubusercontent.com/20397027/64538012-d83c7600-d356-11e9-833b-f1d9648f2382.gif)
(this is running on sway)

To me it must be again another multi-byte Unicode char issue, but from various attempts the bug does not appear to be something we have control over in `i3status-rust`, as changing the value of the block's `max_width` (which is actually `min_width` in [i3 protocol](https://i3wm.org/docs/i3bar-protocol.html) speak) does not seem to affect the occurrence of the bug.

I have a feeling the issue is with how i3 is calculating the width of the text string, probably [this function](https://github.com/i3/i3/blob/a574346964ce17d35df2ef9072ba16e26209ac84/libi3/font.c#L497). It's probably counting the literal bytes, so that makes the width larger when multi-byte Unicode characters are present, which fits the pattern of the bar retracting as the number of multi-byte Unicode characters decrease as seen in the gif above.

I am running `sway` though, so there is a chance this is an issue in its implementation of the i3bar protocol. Could someone running i3 please tell me if they can reproduce this bug?

**Comment by ohk2kt3t4** [comment]
OK so I found the same behaviour occurs with `i3`, and from a bit more poking around it all seems to stem from the fact that the `i3status-rust` rotating text widget deals with "characters" and i3/sway [look to be ](https://github.com/i3/i3/blob/a574346964ce17d35df2ef9072ba16e26209ac84/libi3/font.c#L127)dealing with "pixels", so I don't think it is an upstream bug. 

For further research one could check the output of the function linked above for various strings to see exactly what is going on. I am not sure whether it is a trivial change or not, but if the rotating text widget was changed to rotate based on pixels rather than character count, then it should solve this issue.

**Comment by ammgws** [comment]
I made a little test program to check what pixel width things are calculated with:
https://gist.github.com/ammgws/67bb2211eda58b262f46a6021a5b2a5f

You can see that these emojis are not fixed-width:
```
// prev icon
> ./pxtest "" "FontAwesome"
Width of '' is 14
Using font: FontAwesome⏎    

// play icon
> ./pxtest "" "FontAwesome"
Width of '' is 13
Using font: FontAwesome⏎ 
```

Going to close this issue because AFAIK there's nothing we can do about it.

**Comment by atheriel** [comment]
Nice detective work. It's unfortunate that we can't get a good solution at present.
